#!/bin/bash

echo "======================================"
echo "리뷰 시스템 테스트"
echo "======================================"
echo ""

# 서비스 상태 확인
echo "1. 서비스 상태 확인..."
curl -s http://localhost:3000 > /dev/null
if [ $? -eq 0 ]; then
  echo "✅ 서비스가 정상 작동 중입니다."
else
  echo "❌ 서비스가 응답하지 않습니다."
  exit 1
fi
echo ""

echo "======================================"
echo "브라우저 테스트 가이드"
echo "======================================"
echo ""

echo "📋 1단계: 고객이 견적 요청 및 견적서 수신"
echo "--------------------------------------"
echo "1) 고객 대시보드 접속: http://localhost:3000/dashboard/customer"
echo "2) 계정: customer@test.com / 1234"
echo "3) 상세 견적 요청 생성"
echo "4) 시설이 견적서 전송 (hospital@test.com / 1234)"
echo "5) 고객이 받은 견적서 확인"
echo ""

echo "📋 2단계: 리뷰 작성 ⭐ 핵심 기능"
echo "--------------------------------------"
echo "1) 견적서 상세 페이지에서 '리뷰 작성' 버튼 클릭 (노란색)"
echo "2) 리뷰 작성 모달 확인"
echo "3) 별점 선택 (1-5점, 필수)"
echo "   - ★☆☆☆☆ 매우 불만족"
echo "   - ★★☆☆☆ 불만족"
echo "   - ★★★☆☆ 보통"
echo "   - ★★★★☆ 만족"
echo "   - ★★★★★ 매우 만족"
echo "4) 제목 입력 (선택사항)"
echo "   예: 친절하고 깨끗한 시설이었습니다"
echo "5) 리뷰 내용 작성 (최소 10자 이상, 필수)"
echo "   예: 직원분들이 매우 친절하셨고, 시설도 깨끗했습니다."
echo "       식사 품질이 좋았고, 의료 서비스도 만족스러웠습니다."
echo "6) '리뷰 등록' 버튼 클릭"
echo "7) '관리자 승인 후 공개됩니다' 메시지 확인"
echo ""

echo "📋 3단계: 관리자가 리뷰 승인"
echo "--------------------------------------"
echo "⚠️  현재는 리뷰 등록만 가능합니다."
echo "    향후 추가될 기능:"
echo "    - 관리자 대시보드에 '리뷰 관리' 탭"
echo "    - 대기 중인 리뷰 목록 조회"
echo "    - 리뷰 승인/거부 기능"
echo "    - 부적절한 리뷰 필터링"
echo ""

echo "📋 4단계: 시설이 리뷰 확인 및 답변 (향후 구현)"
echo "--------------------------------------"
echo "⚠️  현재는 API만 구현되어 있습니다."
echo "    향후 추가될 기능:"
echo "    - 시설 대시보드에 '내 리뷰' 섹션"
echo "    - 받은 리뷰 목록 조회"
echo "    - 리뷰에 답변 작성"
echo "    - 평균 별점 표시"
echo ""

echo "======================================"
echo "✅ 구현 완료 기능"
echo "======================================"
echo ""
echo "✔ DB 마이그레이션 (reviews, review_responses 테이블)"
echo "✔ 리뷰 작성 API"
echo "✔ 리뷰 조회 API (시설별, 견적서별)"
echo "✔ 시설 답변 API"
echo "✔ 관리자 승인 API"
echo "✔ 견적서 상세 페이지에 '리뷰 작성' 버튼"
echo "✔ 리뷰 작성 모달 UI"
echo "✔ 별점 선택 (1-5점)"
echo "✔ 실제 이용자 인증 (견적 받은 고객만)"
echo "✔ 중복 리뷰 방지"
echo ""

echo "======================================"
echo "🔧 다음 단계 구현 필요"
echo "======================================"
echo ""
echo "❏ 관리자 대시보드에 리뷰 관리 UI"
echo "❏ 시설 대시보드에 리뷰 관리 섹션"
echo "❏ 견적서 카드에 평균 별점 표시"
echo "❏ 전국 요양시설 찾기에 별점 표시"
echo "❏ 리뷰 목록 페이지"
echo "❏ 사진 첨부 기능 (2단계)"
echo "❏ 도움이 됐어요 기능 (2단계)"
echo ""

echo "======================================"
echo "테스트 URL"
echo "======================================"
echo ""
echo "🌐 고객 대시보드: http://localhost:3000/dashboard/customer"
echo "🌐 시설 대시보드: http://localhost:3000/dashboard/facility"
echo "🌐 관리자 대시보드: http://localhost:3000/admin/dashboard"
echo ""
echo "👤 테스트 계정:"
echo "   고객: customer@test.com / 1234"
echo "   시설: hospital@test.com / 1234"
echo "   관리자: 비밀번호 5874"
echo ""

echo "======================================"
echo "📊 API 엔드포인트"
echo "======================================"
echo ""
echo "POST /api/reviews/create - 리뷰 작성"
echo "GET /api/reviews/facility/:facilityId - 시설별 리뷰 조회"
echo "GET /api/reviews/response/:responseId - 견적서별 리뷰 조회"
echo "POST /api/reviews/respond - 시설 답변"
echo "POST /api/admin/reviews/:reviewId/status - 관리자 승인/거부"
echo "GET /api/admin/reviews/pending - 대기 중인 리뷰 목록"
echo ""
