CREATE TABLE IF NOT EXISTS subscriptions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  plan_type TEXT NOT NULL DEFAULT 'basic',
  status TEXT NOT NULL DEFAULT 'active',
  billing_key TEXT,
  customer_uid TEXT UNIQUE,
  monthly_fee INTEGER NOT NULL DEFAULT 990,
  next_billing_date DATE,
  last_billing_date DATE,
  failed_count INTEGER DEFAULT 0,
  discount_rate INTEGER DEFAULT 30,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  cancelled_at DATETIME,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  imp_uid TEXT UNIQUE,
  merchant_uid TEXT UNIQUE NOT NULL,
  payment_type TEXT NOT NULL,
  payment_method TEXT,
  pg_provider TEXT DEFAULT 'kcp',
  amount INTEGER NOT NULL,
  paid_amount INTEGER,
  cancel_amount INTEGER DEFAULT 0,
  currency TEXT DEFAULT 'KRW',
  status TEXT NOT NULL DEFAULT 'pending',
  paid_at DATETIME,
  failed_at DATETIME,
  cancelled_at DATETIME,
  fail_reason TEXT,
  cancel_reason TEXT,
  subscription_id INTEGER,
  booking_id INTEGER,
  receipt_url TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (subscription_id) REFERENCES subscriptions(id),
  FOREIGN KEY (booking_id) REFERENCES bookings(id)
);

CREATE TABLE IF NOT EXISTS bookings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  facility_id INTEGER,
  patient_name TEXT NOT NULL,
  patient_age INTEGER,
  patient_condition TEXT NOT NULL,
  service_type TEXT NOT NULL,
  service_date DATE NOT NULL,
  service_time TEXT,
  pickup_address TEXT,
  pickup_detail TEXT,
  hospital_name TEXT,
  hospital_address TEXT,
  base_price INTEGER NOT NULL,
  member_discount INTEGER DEFAULT 0,
  final_price INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  partner_id INTEGER,
  assigned_at DATETIME,
  completed_at DATETIME,
  safety_report_url TEXT,
  safety_report_text TEXT,
  special_request TEXT,
  admin_memo TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (facility_id) REFERENCES facilities(id),
  FOREIGN KEY (partner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS partner_profiles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL UNIQUE,
  real_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  certification_type TEXT,
  certification_number TEXT,
  certification_file_url TEXT,
  service_regions TEXT,
  total_bookings INTEGER DEFAULT 0,
  completed_bookings INTEGER DEFAULT 0,
  cancelled_bookings INTEGER DEFAULT 0,
  average_rating REAL DEFAULT 0,
  commission_rate INTEGER DEFAULT 60,
  total_earnings INTEGER DEFAULT 0,
  pending_amount INTEGER DEFAULT 0,
  withdrawn_amount INTEGER DEFAULT 0,
  is_verified INTEGER DEFAULT 0,
  is_active INTEGER DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS partner_settlements (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  partner_id INTEGER NOT NULL,
  booking_id INTEGER NOT NULL,
  booking_amount INTEGER NOT NULL,
  commission_rate INTEGER NOT NULL,
  partner_amount INTEGER NOT NULL,
  platform_fee INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  confirmed_at DATETIME,
  paid_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (partner_id) REFERENCES users(id),
  FOREIGN KEY (booking_id) REFERENCES bookings(id)
);

CREATE TABLE IF NOT EXISTS withdrawal_requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  partner_id INTEGER NOT NULL,
  requested_amount INTEGER NOT NULL,
  bank_name TEXT NOT NULL,
  account_number TEXT NOT NULL,
  account_holder TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  approved_at DATETIME,
  approved_by INTEGER,
  completed_at DATETIME,
  reject_reason TEXT,
  admin_memo TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (partner_id) REFERENCES users(id),
  FOREIGN KEY (approved_by) REFERENCES users(id)
);
